name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install libbsd
      run: sudo apt install -y libbsd-dev
      
    - name: Build executable
      run: make executable
      
    - name: Run tests
      run: make tests
